# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ssh.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SSH(object):
    def setupUi(self, SSH):
        SSH.setObjectName("SSH")
        SSH.resize(360, 36)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SSH)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon = QtWidgets.QLabel(SSH)
        self.icon.setMinimumSize(QtCore.QSize(24, 24))
        self.icon.setMaximumSize(QtCore.QSize(24, 24))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.horizontalLayout.addWidget(self.icon)
        self.name = QtWidgets.QLabel(SSH)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name.setFont(font)
        self.name.setIndent(5)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.action_upload = QtWidgets.QPushButton(SSH)
        self.action_upload.setMaximumSize(QtCore.QSize(32, 16777215))
        self.action_upload.setFocusPolicy(QtCore.Qt.NoFocus)
        self.action_upload.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/upload.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_upload.setIcon(icon)
        self.action_upload.setIconSize(QtCore.QSize(20, 20))
        self.action_upload.setFlat(True)
        self.action_upload.setObjectName("action_upload")
        self.horizontalLayout.addWidget(self.action_upload)
        self.action_download = QtWidgets.QPushButton(SSH)
        self.action_download.setMaximumSize(QtCore.QSize(32, 16777215))
        self.action_download.setFocusPolicy(QtCore.Qt.NoFocus)
        self.action_download.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/download.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_download.setIcon(icon1)
        self.action_download.setIconSize(QtCore.QSize(20, 20))
        self.action_download.setFlat(True)
        self.action_download.setObjectName("action_download")
        self.horizontalLayout.addWidget(self.action_download)
        self.action_settings = QtWidgets.QPushButton(SSH)
        self.action_settings.setMaximumSize(QtCore.QSize(32, 32))
        self.action_settings.setFocusPolicy(QtCore.Qt.NoFocus)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/config.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_settings.setIcon(icon2)
        self.action_settings.setIconSize(QtCore.QSize(20, 20))
        self.action_settings.setFlat(True)
        self.action_settings.setObjectName("action_settings")
        self.horizontalLayout.addWidget(self.action_settings)

        self.retranslateUi(SSH)
        QtCore.QMetaObject.connectSlotsByName(SSH)

    def retranslateUi(self, SSH):
        _translate = QtCore.QCoreApplication.translate
        SSH.setWindowTitle(_translate("SSH", "Form"))
        self.icon.setText(_translate("SSH", "icon"))
        self.name.setText(_translate("SSH", "TextLabel"))
