# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sshconfig.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SSHConfig(object):
    def setupUi(self, SSHConfig):
        SSHConfig.setObjectName("SSHConfig")
        SSHConfig.resize(508, 141)
        self.gridLayout = QtWidgets.QGridLayout(SSHConfig)
        self.gridLayout.setObjectName("gridLayout")
        self.Remote_directory = QtWidgets.QLabel(SSHConfig)
        self.Remote_directory.setObjectName("Remote_directory")
        self.gridLayout.addWidget(self.Remote_directory, 2, 0, 1, 1)
        self.Local_dir = QtWidgets.QLabel(SSHConfig)
        self.Local_dir.setObjectName("Local_dir")
        self.gridLayout.addWidget(self.Local_dir, 0, 0, 1, 1)
        self.Remote_dir_edit = QtWidgets.QLineEdit(SSHConfig)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.Remote_dir_edit.setFont(font)
        self.Remote_dir_edit.setObjectName("Remote_dir_edit")
        self.gridLayout.addWidget(self.Remote_dir_edit, 2, 2, 1, 2)
        self.Remote_ip_edit = QtWidgets.QLineEdit(SSHConfig)
        self.Remote_ip_edit.setObjectName("Remote_ip_edit")
        self.gridLayout.addWidget(self.Remote_ip_edit, 1, 2, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.local_dir_edit = QtWidgets.QLineEdit(SSHConfig)
        self.local_dir_edit.setObjectName("local_dir_edit")
        self.horizontalLayout_2.addWidget(self.local_dir_edit)
        self.openDirButton = QtWidgets.QPushButton(SSHConfig)
        self.openDirButton.setObjectName("openDirButton")
        self.horizontalLayout_2.addWidget(self.openDirButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 2, 1, 2)
        self.Remote_address = QtWidgets.QLabel(SSHConfig)
        self.Remote_address.setObjectName("Remote_address")
        self.gridLayout.addWidget(self.Remote_address, 1, 0, 1, 1)

        self.retranslateUi(SSHConfig)
        QtCore.QMetaObject.connectSlotsByName(SSHConfig)

    def retranslateUi(self, SSHConfig):
        _translate = QtCore.QCoreApplication.translate
        SSHConfig.setWindowTitle(_translate("SSHConfig", "Dialog"))
        self.Remote_directory.setText(_translate("SSHConfig", "Remote Dir"))
        self.Local_dir.setText(_translate("SSHConfig", "Local Dir"))
        self.Remote_dir_edit.setPlaceholderText(_translate("SSHConfig", "/home/{user}/Templates"))
        self.openDirButton.setText(_translate("SSHConfig", "Open"))
        self.Remote_address.setText(_translate("SSHConfig", "Remote Address"))
